name: Deploy Node App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          port: ${{ secrets.VM_SSH_PORT }}
          key: ${{ secrets.VM_SSH_KEY }}

          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

            node -v
            npm -v
            pm2 -v
            
            cd projects/cicd-auto-deploy-demo

            git pull origin main

            npm ci

            pm2 restart node-cicd-demo